# Generated by Django 5.2.10 on 2026-01-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedscan',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
