# Generated by Django 5.2.10 on 2026-02-02 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0003_breed_color_description_breed_daily_yield_and_more'),
        ('recognition', '0002_breedscan_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedscan',
            name='ai_source',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('local', 'Local Model')], default='gemini', max_length=20),
        ),
        migrations.AddField(
            model_name='breedscan',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='breeds.breed'),
        ),
        migrations.AddField(
            model_name='breedscan',
            name='processing_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
