# Generated by Django 5.2.10 on 2026-01-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Cattle', 'Cattle'), ('Buffalo', 'Buffalo')], max_length=10)),
                ('thumbnail', models.ImageField(upload_to='breeds/thumbnails/')),
                ('description', models.TextField()),
                ('origin_location', models.CharField(max_length=150)),
                ('milk_yield', models.CharField(help_text='e.g., 15-20 L/day', max_length=50)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
