# Generated by Django 6.0.1 on 2026-01-30 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['name'], 'verbose_name': 'Breed', 'verbose_name_plural': 'Breeds'},
        ),
        migrations.AddField(
            model_name='breed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='category',
            field=models.CharField(choices=[('Cattle', 'Cattle'), ('Buffalo', 'Buffalo')], default='Cattle', max_length=10),
        ),
        migrations.AlterField(
            model_name='breed',
            name='milk_yield',
            field=models.CharField(help_text='e.g., 15–20 L/day', max_length=50),
        ),
        migrations.AlterField(
            model_name='breed',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail image for dashboard display', null=True, upload_to='breeds/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='video_link',
            field=models.URLField(blank=True, help_text='Optional YouTube or reference video link', null=True),
        ),
    ]
