# Generated by Django 5.2.10 on 2026-02-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0002_alter_breed_options_breed_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='color_description',
            field=models.CharField(blank=True, help_text='e.g., Black & White, Brown, Fawn', max_length=100),
        ),
        migrations.AddField(
            model_name='breed',
            name='daily_yield',
            field=models.CharField(blank=True, help_text='Alternative yield display (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='breed',
            name='milk_fat',
            field=models.CharField(blank=True, help_text='e.g., 4–6%', max_length=20),
        ),
        migrations.AddField(
            model_name='breed',
            name='traits',
            field=models.TextField(blank=True, help_text='Comma separated traits, e.g. Heat tolerant, Disease resistant'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail image for gallery and detail pages', null=True, upload_to='breeds/thumbnails/'),
        ),
    ]
